{
 "title": "My Dashboard",
 "tags": [ "webapp" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 12 },
   "targets": [
    {
     "expr": "rate(http_requests_total[10s])",
     "legendFormat": "{{method}} {{endpoint}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Login Success",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 24, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "rate(http_requests_total{endpoint=\"login\",status_code=\"200\"}[10s])",
     "legendFormat": "{{method}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Login Failures",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 24, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "rate(http_requests_total{endpoint=\"login\",status_code=~\"400|401|500\"}[10s])",
     "legendFormat": "{{method}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Login Rate Limit",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 36, "w": 24, "h": 12 },
   "targets": [
    {
     "expr": "rate(http_requests_total{endpoint=\"auth\",status_code=\"429\"}[10s])",
     "legendFormat": "{{method}} {{status_code}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 48, "w": 24, "h": 12 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(process_cpu_seconds_total[1m])) * 100)",
     "legendFormat": "CPU Usage"
    }
   ]
  }
 ]
}